# Podstawy kontroli wersji przy pomocy Gita

## Podstawowe informacje
System kontroli wersji to narzędzie, które zarządza zmianami wprowadzanymi w plikach i katalogach w projekcie. Istnieje wiele systemów kontroli wersji. Przykładem takiego systemu jest Git. Jego mocne strony to:
  
* Nic, co jest zapisane w Git, nigdy nie jest tracone, więc zawsze możesz wrócić, aby zobaczyć, które wyniki zostały wygenerowane przez które wersje twoich programów.
* Git automatycznie powiadamia Cię, gdy Twoja praca koliduje z pracą innej osoby, więc jest trudniej (choć nie jest to niemożliwe) o przypadkowe nadpisanie pracy.
* Git może synchronizować pracę wykonywaną przez różne osoby na różnych komputerach.

Kontrola wersji nie dotyczy tylko oprogramowania: książki, artykuły, zestawy parametrów i wszystko, co zmienia się w czasie lub wymaga udostępnienia, może i powinno być przechowywane i udostępniane za pomocą czegoś takiego jak Git.

Każdy z projektów Git składa się z dwóch części: plików i katalogów, które tworzysz i edytujesz bezpośrednio, oraz dodatkowych informacji, które Git rejestruje o historii projektu. Połączenie tych dwóch rzeczy nazywa się repozytorium.

Git przechowuje wszystkie dodatkowe informacje w katalogu o nazwie $\texttt{.git}$ znajdującym się w katalogu głównym repozytorium.

## Podstawowe komendy

Używając Gita zapewne często będziemy chcieli sprawdzić stan swojego repozytorium. Aby to zrobić, użyjemy polecenie $\texttt{git status}$.

* $\texttt{git status}$ - wyświetla listę plików, które zostały zmodyfikowane od czasu ostatniego zapisania zmian

Git ma obszar przejściowy, w którym przechowuje pliki ze zmianami, które chcemy zapisać, a które nie zostały jeszcze zapisane.

* $\texttt{git status}$ - pokazuje, które pliki znajdują się w tym obszarze przejściowy i które mają zmiany, które nie zostały jeszcze zatwierdzone

* $\texttt{git diff}$ - pokaże wszystkie zmiany w twoim repozytorium (porównując obecną postać plików z ostatnio zapisaną)
* $\texttt{git diff directory}$ - pokaże zmiany w plikach w jakimś katalogu (porównując obecną postać plików z ostatnio zapisaną)
* $\texttt{git diff filename}$ - pokaże zmiany w danym pliku (porównując obecną postać z ostatnio zapisaną)

Git różnice między dwiema wersjami pliku wyświetla w poniższy sposób:
  ```
diff --git a/report.txt b/report.txt
index e713b17..4c0742a 100644
--- a/report.txt
+++ b/report.txt
@@ -1,4 +1,5 @@
  -# Seasonal Dental Surgeries 2017-18
  +# Seasonal Dental Surgeries (2017) 2017-18
  +# TODO: write new summary
  ```
gdzie:
  
  * $\texttt{a/report.txt, b/report.txt}$ to pierwsza i druga wersja pliku,
* linia druga wypisuje klucze do wewnętrznej bazy danych zmian Gita,
* $\texttt{--- a/report.txt, +++ b/report.txt}$ oznacza, że usuwane linie oznaczone są przedrostkiem $\texttt{-}$, dodawane linie oznaczone są przedrostkiem $\texttt{+}$,
* linia zaczynająca się od $\texttt{@@}$ mówi, gdzie wprowadzane są zmiany. Pary liczb to numer lini ,,startowej'' i liczba linii,
* kolejne linie są listą zmian, które zostały wprowadzone.



* $\texttt{git add filename}$ - dodaje plik do obszaru przejściowego

* $\texttt{git diff -r HEAD}$ - porówna pliki z repozytorium z plikami z obszaru przejściowego
* $\texttt{git diff -r HEAD path/to/file}$ - porówna konkretny plik z repozytorium z plikiem z obszaru przejściowego

* $\texttt{nano filename}$ - otwiera plik w edytorze tekstowym $\texttt{nano}$
  * poruszanie się strzałkami
* $\texttt{Backspace}$ - usuń znak
* $\texttt{Ctrl-K}$: usuń linię
* $\texttt{Ctrl-U}$: cofnij usunięcie linii
* $\texttt{Ctrl-O}$: zapisz plik
* $\texttt{Ctrl-X}$: wyjdź z edytora

* $\texttt{git commit -m "comment"}$ - zapisuje zmiany w obszarze przejściowym z jednowierszowym komunikatem o wprowadzonych zmianach
* $\texttt{git commit --amend - m "new message"}$ - zmienia ostatni komunikat

* $\texttt{git log}$ - wyświetlenie historii projektu (od najnowszych zmian). Wyświetlany zostaje unikatowy identyfikator dla zatwierdzenia oraz informacje na temat tego kto dokonał zmiany, kiedy i jaki komunikat napisał dokonując zmiany.
* $\texttt{spacja}$ - przejcie w dół o stronę
* $\texttt{q}$ - wyjście
* $\texttt{git log path}$ - wyświetlenie historii danego pliku lub katalogu



## Repozytoria    

&nbsp;&nbsp;&nbsp;Informacje dotyczące zatwiedzonych zmian przechowywane są poprzez trzypoziomową strukturę. Każde zatwierdzenie (tzw. *commit*) zwiera komunikat o zatwierdzeniu i informacje o autorze i czasie, w którym zatwierdzenie zmian zostało wykonane. Każdy *commit* ma również swoje drzewo, które śledzi, gdzie w repozytorium dokonano zmian. Dla każdego pliku w drzewie istnieje tzw. *blob* (*binary large object*). Każdy *blob* zawiera skompresowaną migawkę zawartości pliku, z chwili w której nastąpił *commit*.

**Czym jest hash?**   
  
  Każde zatwierdzenie zmian w repozytorium ma unikalny identyfikator zwany **hashem**. Jest on zapisywany jako 40-znakowy ciąg szesnastkowy. Zazwyczaj jednak wystarczy podać pierwsze 6 lub 8 znaków hasha, by odnaleźć konkretne zatwierdzenie (*commit*). Identyfikatory jakimi są hashe umożliwiają Gitowi wydajne udostępnianie danych pomiędzy repozytoriami.   

**Jak wyświetlić konkretny commit?**   
  
  By wyświetlić szczegóły dotyczące konkretnego *commitu* należy użyć komendy **git show** z pierwszymi 6 znakami *hasha* danego *commmitu* np.: *git show Oda2f7*.   

**Czym jest odpowiednik ścieżki względnej w Git?**   

Innym sposobem identyfikacji zatwierdzenia jest użycie odpowiednika ściezki względnej. By wyświetlić zatem ostatni *commit* możemy użyć komendy *git show* z etykietą *HEAD*. Jeśli natomiast zamiast *HEAD* wpiszemy *HEAD~1* wyświetlony zostanie przedostatni *commit*, polecenie *git show HEAD~2* zwróci nam natomiast jeszcze wcześniejszy *commit* itp.  

## Podstawowe komendy  

 
* **git log** - wyświetla całą historię danego pliku lub projektu. W Gicie możemy jednak sprawdzić bardziej szczegółowe informacje. Dzięki poleceniu **git annotate file** możemy sprawdzić kto i kiedy dokonał ostatniej zmiany w każdej linijce pliku.  

* **git diff ID1..ID2** - umożliwia sprawdzenie zmian pomiędzy dwoma commitami, których identyfikatory to odpowiednio ID1 i ID2.

* **git add** - polecenie umożliwiające dodanie nowego pliku. Po wykonaniu tego polecenia Git zaczyna śledzić dodany plik. 

* **git clean -n** - pokazuje listę plików, które są w repozytorium, ale których historia nie jest śledzona przez Gita. 

* **git clean -f** - usuwa pliki, które są w repozytorium i których historii nie śledzi Git. Z używaniem tego polecenia należy uważać, ponieważ usuwa ono pliki z pamięci na stałe i nie da się ich już odzyskać.    

* **git config - -list** - wyświetla ustawienia Gita.   

* **git config - -system** - wyświetla ustawienia każdego użytkownika na danym komputerze.  

* **git config - -global** - wyświetla ustawienia każdego projektu.   

* **git config - -local** - wyświetla ustawienia poszczególnego projektu.  

Każdy poziom zastępuje poziom nad nim, więc ustawienia lokalne (na projekt) mają pierwszeństwo przed ustawieniami globalnymi (na użytkownika), które z kolei mają pierwszeństwo przed ustawieniami systemowymi (dla wszystkich użytkowników na komputerze).

* **git config - -global setting value** - zmienia konfigurację odpowiedniej wartości dla wszystkich projektów na danym komputerze. Jako *setting* należy wpisać to co chcemy zmienić (np. *user.name*, *user.email*  itp.), a jako *value* to co chcemy ustawić.  

##  Cofanie zmian 

Teraz dowiemy się jak cofnąć wprowadzone zmiany.  

* $\texttt{git reset HEAD}$- usuwa ostatnio dodany  plik ze śledzenia,    

* $\texttt{git checkout -- filename}$ - odrzuci zmiany, które nie zostały jeszcze dodane do śledzenia,  

* $\texttt{git reset HEAD path/to/file}$ - odrzuci ostatnie  zmiany w pliku, który został juz dodany do śledzenia,   

* $\texttt{git checkout 2242bd filename}$- zamienia aktualna wersje pliku, na tę o hashu '2242bd'.   

Do ostatniej komendy przydatne może być wykonanie poniższzego polecenia, aby sprawdzić hashe plików.   

* $\texttt{git log - 3 filename}$- pokaże 3 ostatnie commity dotyczące wskazanego pliku.

Poniższe dwie komendy pokazują, jak cofać zmiany na więcej niż jednym pliku.    

* $\texttt{git reset HEAD data}$- usuwa ze śledzenia wszystkie pliki z katalogu data. Jeżeli nie podamy nazwy katalogu( wtedy wystarczy samo $\texttt{git reset}$) wszystkie pliki zostaną usunięte. 

* $\texttt{git checkout -- data}$- wszystkie pliki w katalagu data zostaną cofnięte do poprzednich wersji.   

## Gałęzie


Jeśli nie używasz kontroli wersji, typowym przepływem pracy jest tworzenie różnych podkatalogów do przechowywania różnych wersji projektu w różnych stanach, na przykład deweloperskich i końcowych. Oczywiście zawsze kończy się to ostateczną aktualizacją i ostateczną aktualizacją-poprawioną. Problem polega na tym, że trudno jest to rozwiązać, jeśli masz odpowiednią wersję każdego pliku w odpowiednim podkatalogu i ryzykujesz utratę pracy.
\   
\   
Jednym z powodów, dla których Git jest popularny, jest jego obsługa tworzenia gałęzi (*branchy*), co pozwala na posiadanie wielu wersji Twojej pracy i pozwala na systematyczne śledzenie każdej wersji.
\   
\   
Każda gałąź jest jak wszechświat równoległy: zmiany, które wprowadzasz w jednej gałęzi, nie wpływają na inne gałęzie (dopóki nie połączysz ich z powrotem).
\    
\   
Domyślnie kazde repozytorium Gita ma branch zwany **master**.
\   
\   
Podstawowe komendy związanie z działaniem na branchach (gałęziach): \   

* $\texttt{git branch}$ - pokazuje wszystkie branche w repozytorium (branch, w którym obecnie się znajdujesz będziesz wylistowany z $*$). \   

* $\texttt{git diff branch1..branch2}$ - wyświetla różnice między dwoma branchami \   

*Ciekawostka:*    
  
  * $\texttt{git diff branch1..branch2}$ - -$\texttt{shortstat}$ - wyświetla konkretną liczbę plików które się różnią między dwoma branchami\   

* $\texttt{git checkout branch1}$ - pozwala przełączyć się na *branch1*\   

* $\texttt{git checkout -b branch-name}$ - pozwala utworzyć nowego brancha o nazwie *branch-name*\   
\   
Rozgałęzianie pozwala tworzyć równoległe wszechświaty. Scalanie (**merging**) to sposób, w jaki łączysz je z powrotem. Kiedy łączysz jedną gałąź (nazwijmy ją źródłową) z inną (nazwijmy ją docelową), Git włącza zmiany wprowadzone w gałęzi źródłowej do gałęzi docelowej. Jeśli te zmiany nie nakładają się, wynikiem jest nowe zatwierdzenie w gałęzi docelowej, które zawiera wszystko z gałęzi źródłowej. Do mergowania dwóch gałęzi używamy polecenia: \   

* $\texttt{git merge source destination}$ - mergowanie dwóch branchy w jeden\   

Czasami zmiany w dwóch gałęziach będą ze sobą kolidować: na przykład poprawki błędów mogą dotyczyć tych samych wierszy kodu lub analizy w dwóch różnych gałęziach mogą dołączać nowe (i różne) rekordy do pliku danych podsumowania. W takim przypadku ty decydujesz o sprzeczności zmian.\   
\   
Jeżeli podczas mergowania występuje konflikt Git informuje Cię, że wystapił problem a $\texttt{git status}$ poinformuje Cię, które pliki wmagają rozwiązania konfliktów.\   
\   
Git pozostawia na danym pliku znaczniki, aby poinformować Cię o konkretnym miejscu konfliktu. Znaczniki te wyglądają następująco:
  ```
<<<<<<< destination-branch-name
...changes from the destination branch...
=======
  ...changes from the source branch...
>>>>>>> source-branch-name
```
\   
Aby rozwiązać konflikt edytuj plik, usuwając znaczniki i wprowadź wszelkie zmiany potrzbne do rozwiązania kofilktu, a następnie zrób *commit* tych zmian.\   
\   

## Tworzenie własnych repozytoriów

Przejdźmy do kolejnego zagadnienia związanego z pracą w Gicie. \   
\   
Do tej pory wszystkie poznane funkcje Gita dotyczyły działań na repozytoriach już istniejących. Aby stworzyć własne repozytorium w bieżącym katalogu roboczym wystarczy komenda:\   

* $\texttt{git init project-name}$ \   

Warto wspomnieć, że chociaż Git pozwala tworzyć zagnieżdżone repozytoria nie powinieneś tego robić. Aktualizacja takich repozytoriów bardzo szybko staje się bardzo skomplikowana, ponieważ musisz powiedzieć Gitowi, w którym z dwóch katalogów .git ma być przechowywana aktualizacja.\   
\   
*Nie tworzymy repozytorium w innym już istniejącym!* \   
\   
Poniżej kilka ważnych komend:\   

* $\texttt{git init}$ - inicjalizacja repozytorium w bieżącym katalogu \   

* $\texttt{git init /path/to/project}$ - inicjalizacja repozytorium we wskazanym ścieżką katalogu \   

* $\texttt{git clone URL}$ - tworzenie kopii istniejącego pod wskazanym adresem *URL*  repozytorium    

* $\texttt{git clone /existing/project newprojectname}$ - tworzenie kopii istniejącego repozytroium o zadanej nazwie - *newprojectname* \   

* $\texttt{git remote}$ - wyświetla informację o fizycznej lokalizacji na serwerze Gita, z której zostało sklonowane repo \   

* $\texttt{git remote -v}$ - wyświetla informację o *URL* serwerze Gita, z którego zostało sklonowane repo \   

* $\texttt{git remote add remote-name URL}$ - pozawala na dodanie własnego remota z podanego *URL*    
  
  * $\texttt{git remote rm remote-name}$ - usuwanie istniejącego remota \   

* $\texttt{git pull remote branch}$ - pobieranie zmian w *branchu* w lokalnym repozytorium i mergowanie ich z bieżacym brnachem w lokalnym repozytorium \   

**Uwaga!** \   

*Git powstrzymuje Cię przed pobieraniem ze zdalnego repozytorium zmian, które mogą nadpisać niezapisane lokalnie zmiany. Wystarczy zrobić* commit *tych zmian lub cofnąć je, a następnie spullować repo ponownie. * \   

* $\texttt{git push remote-name branch-name}$ - pushuje zmiany wprowadzone lokalnie na danym branchu do zdalnego repozytorium \   
